# Generated by Django 4.2.7 on 2026-05-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
